name: Build with SGDK

on:
  pull_request:
  push:
    branches:
      - sgdk
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Assets
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: Stephane-D
        repo: SGDK
        tag: v1.51
        file: sgdk151.7z

    - name: extract-7z-action
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: sgdk151.7z
        pathTarget: sgdk
        
    - name: Run SGDK
      run: $GDK_WIN/bin/make -f $GDK_WIN/makefile.gen
      env:
        GDK_WIN: sgdk

    - name: Upload the Rom
      uses: actions/upload-artifact@v2.2.0
      with:
        name: rom.bin
        path: out/rom.bin
        if-no-files-found: error

